### ISSUE TITLE
[Doc] Documentation with environment descriptions

### ISSUE THREAD

**Issue by cbhua** [kaist-silab/rl4co#28]
It would be better to have a document/readme/notebook to describe the environmental problem in detail. Since there are many details for those problems should be clear. For example, can the salesman in the PCTSP visit the depot multi times, should the salesman always come back to the depot for every problem (theoretically should), etc. 

This can also include some details in our implementation to help people understand our code better. For example, when we set the trip to be done in the PCTSP, etc. 

This is temp in low priority before we finish the repo implementation (I can help during the paper-writing period).

**Comment by fedebotu** [comment]
Closing now, will be done in docs 👍
