### ISSUE TITLE
[BUG] SharedBaseline on_dim default value should be -1

### ISSUE THREAD

**Issue by hyeok9855** [kaist-silab/rl4co#92]
## Describe the bug

I think in the SharedBaseline, `on_dim` [here](https://github.com/kaist-silab/rl4co/blob/3a416c393c9bd5afc7a3c14f53212fc0ba6d164e/rl4co/models/rl/reinforce/baselines.py#L56) default value should be -1

If not, it raises 👇
![image](https://github.com/kaist-silab/rl4co/assets/40595684/2faa39e4-a02f-4bd0-9750-b298a56341af)

## To Reproduce

Simply change the baseline and run

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by fedebotu** [comment]
How are you changing the baseline? 
If you use `SharedBaseline`, you should also use some inference techniques (e.g. multistarts for POMO or augmentation for SymNCO), so if you just use the default model with `baseline="shared"`, it will not work. This is why the reward is always converted to [batch, num_pomo/num_aug]

**Comment by hyeok9855** [comment]
Okay I see. But actually I wanted to use just the mean of reward as a naive baseline.
So in this case, should I implement this locally?

**Comment by fedebotu** [comment]
I see! Then feel free to submit a PR ;)
